In [13]:
import numpy as np

In [35]:
class Line:
    
    x0, y0 = None, None
    x1, y1 = None, None
    txt = None

    def __init__(self, txt:str):

        txt = txt.split(' -> ')

        x0 = int(txt[0].split(',')[0])
        y0 = int(txt[0].split(',')[1])
        x1 = int(txt[1].split(',')[0])
        y1 = int(txt[1].split(',')[1])

        self.x0 = x0
        self.y0 = y0
        self.x1 = x1
        self.y1 = y1

        self.min_x = min(x0, x1)
        self.max_x = max(x0, x1)
        self.min_y = min(y0, y1)
        self.max_y = max(y0, y1)

        self.txt = txt
        return
    
    def __str__(self):
        
        return "line ({0},{1}) -> ({2},{3})".format(self.x0, self.y0, self.x1, self.y1)
    
    def __repr__(self):
        return self.__str__()


    def get_xrange(self):

        xrange = np.arange(self.min_x, self.max_x+1)

        if self.x0 > self.x1:
            xrange = xrange[::-1]
        return xrange

    def get_yrange(self):

        yrange = np.arange(self.min_y, self.max_y+1)

        if self.y0 > self.y1:
            yrange = yrange[::-1]
        return yrange   

    def is_vertical(self):
        return self.x0 == self.x1

    def is_horizontal(self):
        return self.y0 == self.y1

    def is_diagonal(self):

        if self.is_vertical() or self.is_horizontal():
            return False

        step_x = self.max_x - self.min_x
        step_y = self.max_y - self.min_y

        return step_x == step_y


# Validation

In [63]:
data = open('validation.csv', 'r').read().split('\n')

In [64]:
# Generate the data
lines = [Line(record) for record in data]

# Grid size
xmax = max([max(line.x0, line.x1) for line in lines]) + 1
ymax = max([max(line.y0, line.y1) for line in lines]) + 1

# Run the ft
canvas = np.zeros((ymax, xmax))
for line in lines:
    
    if line.is_horizontal():
        canvas[line.max_y, line.min_x:line.max_x+1] += 1
    
    if line.is_vertical():
        canvas[line.min_y:line.max_y+1, line.max_x] += 1    
        
    if line.is_diagonal():
        print(line)
        xrange = line.get_xrange()
        yrange = line.get_yrange()

        for position in zip(xrange, yrange):
            canvas[position[1], position[0]] += 1
        
number_of_points = (canvas >= 2).sum()
print(number_of_points)

line (8,0) -> (0,8)
line (6,4) -> (2,0)
line (0,0) -> (8,8)
line (5,5) -> (8,2)
12


In [65]:
print(canvas)

[[1. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 2. 0. 2. 0. 0.]
 [0. 1. 1. 2. 3. 1. 3. 2. 1. 1.]
 [0. 0. 0. 1. 0. 2. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]


# Actual

In [53]:
data = open('actual.csv', 'r').read().split('\n')

In [61]:
# Generate the data
lines = [Line(record) for record in data]

# Grid size
xmax = max([max(line.x0, line.x1) for line in lines]) + 1
ymax = max([max(line.y0, line.y1) for line in lines]) + 1

# Run the ft
canvas = np.zeros((ymax, xmax))
for line in lines:
    
    if line.is_horizontal():
        canvas[line.max_y, line.min_x:line.max_x+1] += 1
    
    if line.is_vertical():
        canvas[line.min_y:line.max_y+1, line.max_x] += 1    
        
    if line.is_diagonal():
        xrange = line.get_xrange()
        yrange = line.get_yrange()

        for position in zip(xrange, yrange):
            canvas[position[1], position[0]] += 1
        
number_of_points = (canvas >= 2).sum()
print(number_of_points)

20898


In [57]:
print(canvas)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
